### ISSUE TITLE
does not work with vita-udcd-uvc plugin

### ISSUE THREAD

**Issue by JoeTheTitan** [isage/vivid#3]
ViViD does not connect to my ps3 unless I disable the vita-udcd-uvc plugin.

**Comment by isage** [comment]
Ok, and? You can't have two usb-client plugins working simultaneously.

**Comment by JoeTheTitan** [comment]
Yes you can. [Vitashell](https://github.com/TheOfficialFloW/VitaShell) does this (fixed around [version 1.95](https://github.com/TheOfficialFloW/VitaShell/tree/1.95)). It would be a great feature if you can implement it.

**Comment by JoeTheTitan** [comment]
Sorry for any confusion, can you make it so it stops udcd_uvc and then allows ViViD to work? there is no harm in disabling udcd_uvc because you cannot record a PSVita when connected to a PS3. then when you stop using ViViD then the udcd_uvc plugi starts to work again.
