### ISSUE TITLE
Back touch buttons fail to register fast enough.

### ISSUE THREAD

**Issue by XarceChronus** [isage/vivid#5]
When playing a game like God of War, it is almost impossible to use the R2 button prompts to lift anything.
For whatever reason, the game does not register enough inputs despite me button mashing the hell out of the back touch screen.

Rarely do I get successful.

To reproduce this issue:
Open God of war, make it to the second level up until you find a statue you must kick down.
You will find that mashing R2 on the back touch pad will be almost impossible.
I don't know how I managed to get past these prompts, but there are very rare cases where it does register enough inputs, but most of the time it won't.

**Comment by isage** [comment]
L2 and R2 are analog. So you have to either do sliding motions from top, or tap lower.
