### ISSUE TITLE
After Disconnect vivid no longer works without reboot

### ISSUE THREAD

**Issue by XarceChronus** [isage/vivid#7]
For some reason, if I unplug the cable or quit the application or even press select and start to stop controller functionality vivid will be unable to reconnect to the PS3.
The only way to fix this for me is to reboot the device completely.
Even closing and re opening vivid does not work.

**Comment by isage** [comment]
Can't reproduce. Both disconnecting or pressing start+select to stop and then pressing X to start again works fine.
Make sure you don't use other usb plugins like udcd_uvc

**Comment by isage** [comment]
Have you tried different usb cable?
What fw your ps3 on?
Can you attach your ur0:tai/config.txt from vita?

**Comment by XarceChronus** [comment]
CFW is evilnat beta 10 I thinks..
Ofw is 4.91![config.txt](https://github.com/user-attachments/files/17194827/config.txt)

Here's the tai config
