### ISSUE TITLE
Does not work in safe mode

### ISSUE THREAD

**Issue by XarceChronus** [isage/vivid#8]
Self explanatory, you cannot use this is when your PS3 is in safe mode. 
I would like to use it in safe mode whenever possible as to enable use of the debug HDD exchange utility with the vita

(I do not currently possess a ps3 controller)

**Comment by isage** [comment]
https://github.com/user-attachments/assets/22065ade-9ad3-40b0-bcbf-f298d3028511

Works fine for me. Make sure you aren't using other usb plugins like udcd_uvc
